#ifndef _CRE2_CONFIG_H
#define _CRE2_CONFIG_H

#define STR_VALUE(arg)      #arg
#define FUNCTION_NAME(name) STR_VALUE(name)

#define cre2_VERSION_INTERFACE_CURRENT 0
#define cre2_VERSION_INTERFACE_REVISION 0
#define cre2_VERSION_INTERFACE_AGE 0
const char *cre2_VERSION_INTERFACE_STRING = STR_VALUE(cre2_VERSION_INTERFACE_CURRENT) "." STR_VALUE(cre2_VERSION_INTERFACE_REVISION);
//#define cre2_VERSION_INTERFACE_STRING #cre2_VERSION_INTERFACE_CURRENT "." #cre2_VERSION_INTERFACE_REVISION

#endif
